#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export tmp_zones="$(mktemp -d -t XXXXXX)"
  aws regions | runmany 4 '$1 ec2 describe-availability-zones > "$tmp_zones/$1.json"' 
  (set +f; cat "$tmp_zones"/*.json) | jq -r '.AvailabilityZones[] | "\(.RegionName) \(.ZoneName)"'
}

source sub "$BASH_SOURCE" "$@"
