#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aws ec2 describe-images --owners 099720109477 \
    --filters Name=virtualization-type,Values=hvm \
              Name=state,Values=available \
              Name=architecture,Values=x86_64 \
              Name=block-device-mapping.volume-type,Values=gp2 \
    | jq -r --arg distro xenial '[.Images | sort_by(.CreationDate)[] | select(.Name | test("^ubuntu/images/")) | select(.Name | test("ubuntu-\($distro)"))] | last | .ImageId'
}

source sub "$BASH_SOURCE" "$@"
