#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  exec $shome/../aws-vault/bin/aws-vault "$@"
}

source sub "$BASH_SOURCE" "$@"
