#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  # region
  local nm_region=
  if [[ -n "${1:-}" ]]; then
    nm_region="$1"; shift
   AWS_DEFAULT_PROFILE="$nm_region"
  fi

  export AWS_DEFAULT_PROFILE
  export BASEBOX_SUFFIX="-$AWS_DEFAULT_PROFILE"

  # target aminame
  EC2_TARGET_AMI_NAME="packer-${AWS_DEFAULT_PROFILE}-$(date +%s)"
  export EC2_TARGET_AMI_NAME

  if [[ "$#" -gt 0 ]]; then
    EC2_INSTANCE_TYPE="$1"; shift
  else
    case "$AWS_DEFAULT_PROFILE" in
      sa-east-1)
        EC2_INSTANCE_TYPE='c3.large'
        ;;
      *)
        EC2_INSTANCE_TYPE='c4.large'
        ;;
    esac
  fi
  export EC2_INSTANCE_TYPE

  # source ami
  source "$shome/script/aws_ami"

  eval EC2_SOURCE_AMI="\$${AWS_DEFAULT_PROFILE//-/_}"
  export EC2_SOURCE_AMI

  # build it
  exec parity build ubuntu "$@"
}

source sub "$BASH_SOURCE" "$@"
