#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aws ec2 describe-images --owners 099720109477 \
    --filters Name=virtualization-type,Values=hvm \
              Name=state,Values=available \
              Name=architecture,Values=x86_64 \
              Name=block-device-mapping.volume-type,Values=gp2 \
    | jq -r '.Images | sort_by(.CreationDate)[] | "\(.ImageId) \(.OwnerId) \(.Name) \(.VirtualizationType) \(.BlockDeviceMappings[0].Ebs.VolumeType) \(.Architecture) \(.CreationDate)"' \
    | grep ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server | awk '{ ami=$1 } END { print ami }'

}

source sub "$BASH_SOURCE" "$@"
