#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aws ec2 describe-availability-zones | jq -r '.AvailabilityZones[].ZoneName'
}

source sub "$BASH_SOURCE" "$@"
