#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  local nm_region="$(aws configure get region)"
  export AWS_REGION="${nm_region}"

  export BASEBOX_SUFFIX="-${nm_region}"

  # target aminame
  EC2_TARGET_AMI_NAME="packer-${nm_region}-$(date +%s)"
  export EC2_TARGET_AMI_NAME

  if [[ "$#" -gt 0 ]]; then
    EC2_INSTANCE_TYPE="$1"; shift
  else
    EC2_INSTANCE_TYPE="m3.medium"
  fi
  export EC2_INSTANCE_TYPE

  export EC2_SOURCE_AMI="$(aws ami)"

  # build it
  exec parity build ubuntu "$@"
}

source sub "$BASH_SOURCE" "$@"
