#!/usr/bin/env bash

set -efu

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  pkg ensure textproc/py35-cElementTree textproc/py-cElementTree

  block compile virtualenv
  block compile npm
  ln -nfs ../node_modules/.bin/assume-aws-role "$shome/bin/"
}

main "$@"
