#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  mkdir -p "$shome/bin"
  
  block compile pipenv
  (cd bin && ln -nfs "$(pipenv run which aws)" awscli )
  (cd bin && ln -nfs "$(pipenv run which aws-encryption-cli)" .)

  block compile yarn
  (set +f; cd bin; ln -nfs ../node_modules/.bin/awsmobile* .)
}

main "$@"
