#!/usr/bin/env bash

function profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$shome/vendor/virtualenv/bin:$PATH"
}

profile
