#!/usr/bin/env bash

# see https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

function _aws_profile {
  local shome="${_aws_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  
  export AWS_DEFAULT_OUTPUT='json'
}

_aws_profile
