#!/usr/bin/env bash

function main {
  local shome="${_aws_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$shome/vendor/virtualenv/bin/aws" ]]; then
    return 1
  else
    return 0
  fi
}

source sub "$0" "$@"
