#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_aws="$(aws --version  | awk '{print $1}' | cut -d/ -f2 || true)"
  jq -n --arg aws "$ver_aws" '{aws: $aws}'
}

version "$@"
